# Generated by Django 6.0.4 on 2026-04-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emoji', models.CharField(default='🎵', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('file', 'MP3 File'), ('youtube', 'YouTube'), ('soundcloud', 'SoundCloud')], default='file', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tracks/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_url', models.URLField(blank=True, default='')),
                ('duration', models.CharField(blank=True, default='0:00', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.track')),
            ],
            options={
                'ordering': ['order', 'added_at'],
                'unique_together': {('playlist', 'track')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, through='main.PlaylistTrack', to='main.track'),
        ),
        migrations.CreateModel(
            name='LikedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='main.track')),
            ],
            options={
                'ordering': ['-liked_at'],
            },
        ),
    ]
